version: '3'

services:
  qubic-archiver:
    image: ghcr.io/qubic/qubic-archiver:v0.1.18
    container_name: qubic-archiver
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.qubic-archiver.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.routers.qubic-archiver.rule=Host(`testapi.qubic.org`)"
      - "traefik.http.routers.qubic-archiver.entrypoints=web"
      - "traefik.http.routers.qubic-archiver.middlewares=qubic-archiver"
      - "traefik.http.services.qubic-archiver.loadbalancer.server.port=8000"

    ports:
      - "127.0.0.1:8001:8001"
    environment:
      QUBIC_ARCHIVER_SERVER_HTTP_HOST: "0.0.0.0:8000"
      QUBIC_ARCHIVER_SERVER_GRPC_HOST: "0.0.0.0:8001"
      QUBIC_ARCHIVER_POOL_NODE_FETCHER_URL: "http://qubic-node-fetcher:8080/peers"
      QUBIC_ARCHIVER_QUBIC_PROCESS_TICK_TIMEOUT: "20s"
    volumes:
      - ./store/archiver:/app/store
    networks:
      - traefik
    depends_on:
      qubic-node-fetcher:
        condition: service_healthy
    restart: always

  qubic-node-fetcher:
    image: ghcr.io/qubic/go-node-fetcher:v0.1.1
    container_name: qubic-node-fetcher
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      NODE_FETCHER_QUBIC_STARTING_PEER_IP: "212.51.150.253"
    volumes:
      - ./store/node-fetcher:/app/store
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://qubic-node-fetcher:8080/peers"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "127.0.0.1:8081:8080"
    depends_on:
      - "qubic-archiver"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    restart: always

networks:
  traefik: