version: '3'

services:
  qubic-archiver:
    image: ghcr.io/qubic/qubic-archiver:v0.1.17
    container_name: qubic-archiver
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
    depends_on:
      qubic-node-fetcher:
        condition: service_healthy
    environment:
      QUBIC_ARCHIVER_SERVER_HTTP_HOST: "0.0.0.0:8000"
      QUBIC_ARCHIVER_SERVER_GRPC_HOST: "0.0.0.0:8001"
      QUBIC_ARCHIVER_POOL_NODE_FETCHER_URL: "http://qubic-node-fetcher:8080/peers"
    volumes:
      - ./store/archiver:/app/store
    networks:
      - qubic
    restart: always

  qubic-node-fetcher:
    image: ghcr.io/qubic/go-node-fetcher:v0.1.1
    container_name: qubic-node-fetcher
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      NODE_FETCHER_QUBIC_STARTING_PEER_IP: "212.51.150.253"
    volumes:
      - ./store/node-fetcher:/app/store
    networks:
      - qubic
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://qubic-node-fetcher:8080/peers"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

networks:
  qubic: