// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: heatwallet.proto

/*
Package proto is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package proto

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

var filter_HeatwalletService_GetIdentityAssetTransactionsV2_0 = &utilities.DoubleArray{Encoding: map[string]int{"identity": 0, "asset_issuer": 1, "asset_name": 2}, Base: []int{1, 1, 2, 3, 0, 0, 0}, Check: []int{0, 1, 1, 1, 2, 3, 4}}

func request_HeatwalletService_GetIdentityAssetTransactionsV2_0(ctx context.Context, marshaler runtime.Marshaler, client HeatwalletServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetIdentityAssetTransactionsRequestV2
		metadata runtime.ServerMetadata
		err      error
	)
	io.Copy(io.Discard, req.Body)
	val, ok := pathParams["identity"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "identity")
	}
	protoReq.Identity, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "identity", err)
	}
	val, ok = pathParams["asset_issuer"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "asset_issuer")
	}
	protoReq.AssetIssuer, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "asset_issuer", err)
	}
	val, ok = pathParams["asset_name"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "asset_name")
	}
	protoReq.AssetName, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "asset_name", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HeatwalletService_GetIdentityAssetTransactionsV2_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetIdentityAssetTransactionsV2(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_HeatwalletService_GetIdentityAssetTransactionsV2_0(ctx context.Context, marshaler runtime.Marshaler, server HeatwalletServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetIdentityAssetTransactionsRequestV2
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["identity"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "identity")
	}
	protoReq.Identity, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "identity", err)
	}
	val, ok = pathParams["asset_issuer"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "asset_issuer")
	}
	protoReq.AssetIssuer, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "asset_issuer", err)
	}
	val, ok = pathParams["asset_name"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "asset_name")
	}
	protoReq.AssetName, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "asset_name", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HeatwalletService_GetIdentityAssetTransactionsV2_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetIdentityAssetTransactionsV2(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterHeatwalletServiceHandlerServer registers the http handlers for service HeatwalletService to "mux".
// UnaryRPC     :call HeatwalletServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterHeatwalletServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterHeatwalletServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server HeatwalletServiceServer) error {
	mux.Handle(http.MethodGet, pattern_HeatwalletService_GetIdentityAssetTransactionsV2_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/qubic.archiver.archive.pb.HeatwalletService/GetIdentityAssetTransactionsV2", runtime.WithHTTPPathPattern("/v2/identities/{identity}/{asset_issuer}/{asset_name}/asset-transactions"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HeatwalletService_GetIdentityAssetTransactionsV2_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_HeatwalletService_GetIdentityAssetTransactionsV2_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterHeatwalletServiceHandlerFromEndpoint is same as RegisterHeatwalletServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterHeatwalletServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterHeatwalletServiceHandler(ctx, mux, conn)
}

// RegisterHeatwalletServiceHandler registers the http handlers for service HeatwalletService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterHeatwalletServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterHeatwalletServiceHandlerClient(ctx, mux, NewHeatwalletServiceClient(conn))
}

// RegisterHeatwalletServiceHandlerClient registers the http handlers for service HeatwalletService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "HeatwalletServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "HeatwalletServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "HeatwalletServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterHeatwalletServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client HeatwalletServiceClient) error {
	mux.Handle(http.MethodGet, pattern_HeatwalletService_GetIdentityAssetTransactionsV2_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/qubic.archiver.archive.pb.HeatwalletService/GetIdentityAssetTransactionsV2", runtime.WithHTTPPathPattern("/v2/identities/{identity}/{asset_issuer}/{asset_name}/asset-transactions"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HeatwalletService_GetIdentityAssetTransactionsV2_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_HeatwalletService_GetIdentityAssetTransactionsV2_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_HeatwalletService_GetIdentityAssetTransactionsV2_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 1, 0, 4, 1, 5, 3, 1, 0, 4, 1, 5, 4, 2, 5}, []string{"v2", "identities", "identity", "asset_issuer", "asset_name", "asset-transactions"}, ""))
)

var (
	forward_HeatwalletService_GetIdentityAssetTransactionsV2_0 = runtime.ForwardResponseMessage
)
