// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: heatwallet.proto

package proto

import (
	protobuff "github.com/qubic/go-archiver/protobuff"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetTransactionType int32

const (
	AssetTransactionType_NATIVE_TRANSFER   AssetTransactionType = 0
	AssetTransactionType_QUTIL_SEND_MANY   AssetTransactionType = 1
	AssetTransactionType_QX_ASSET_TRANSFER AssetTransactionType = 2
)

// Enum value maps for AssetTransactionType.
var (
	AssetTransactionType_name = map[int32]string{
		0: "NATIVE_TRANSFER",
		1: "QUTIL_SEND_MANY",
		2: "QX_ASSET_TRANSFER",
	}
	AssetTransactionType_value = map[string]int32{
		"NATIVE_TRANSFER":   0,
		"QUTIL_SEND_MANY":   1,
		"QX_ASSET_TRANSFER": 2,
	}
)

func (x AssetTransactionType) Enum() *AssetTransactionType {
	p := new(AssetTransactionType)
	*p = x
	return p
}

func (x AssetTransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetTransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_heatwallet_proto_enumTypes[0].Descriptor()
}

func (AssetTransactionType) Type() protoreflect.EnumType {
	return &file_heatwallet_proto_enumTypes[0]
}

func (x AssetTransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetTransactionType.Descriptor instead.
func (AssetTransactionType) EnumDescriptor() ([]byte, []int) {
	return file_heatwallet_proto_rawDescGZIP(), []int{0}
}

type AssetTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionType AssetTransactionType   `protobuf:"varint,1,opt,name=transaction_type,json=transactionType,proto3,enum=qubic.archiver.archive.pb.AssetTransactionType" json:"transaction_type,omitempty"`
	Transaction     *protobuff.Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp       uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MoneyFlew       bool                   `protobuf:"varint,4,opt,name=money_flew,json=moneyFlew,proto3" json:"money_flew,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AssetTransaction_QutilSendMany
	//	*AssetTransaction_QxAssetTransfer
	Payload       isAssetTransaction_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetTransaction) Reset() {
	*x = AssetTransaction{}
	mi := &file_heatwallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetTransaction) ProtoMessage() {}

func (x *AssetTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_heatwallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetTransaction.ProtoReflect.Descriptor instead.
func (*AssetTransaction) Descriptor() ([]byte, []int) {
	return file_heatwallet_proto_rawDescGZIP(), []int{0}
}

func (x *AssetTransaction) GetTransactionType() AssetTransactionType {
	if x != nil {
		return x.TransactionType
	}
	return AssetTransactionType_NATIVE_TRANSFER
}

func (x *AssetTransaction) GetTransaction() *protobuff.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *AssetTransaction) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AssetTransaction) GetMoneyFlew() bool {
	if x != nil {
		return x.MoneyFlew
	}
	return false
}

func (x *AssetTransaction) GetPayload() isAssetTransaction_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AssetTransaction) GetQutilSendMany() *protobuff.SendManyTransaction {
	if x != nil {
		if x, ok := x.Payload.(*AssetTransaction_QutilSendMany); ok {
			return x.QutilSendMany
		}
	}
	return nil
}

func (x *AssetTransaction) GetQxAssetTransfer() *AssetTransactionQxTransfer {
	if x != nil {
		if x, ok := x.Payload.(*AssetTransaction_QxAssetTransfer); ok {
			return x.QxAssetTransfer
		}
	}
	return nil
}

type isAssetTransaction_Payload interface {
	isAssetTransaction_Payload()
}

type AssetTransaction_QutilSendMany struct {
	QutilSendMany *protobuff.SendManyTransaction `protobuf:"bytes,5,opt,name=qutil_send_many,json=qutilSendMany,proto3,oneof"`
}

type AssetTransaction_QxAssetTransfer struct {
	QxAssetTransfer *AssetTransactionQxTransfer `protobuf:"bytes,6,opt,name=qx_asset_transfer,json=qxAssetTransfer,proto3,oneof"`
}

func (*AssetTransaction_QutilSendMany) isAssetTransaction_Payload() {}

func (*AssetTransaction_QxAssetTransfer) isAssetTransaction_Payload() {}

type AssetTransactionQxTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetIssuer   string                 `protobuf:"bytes,1,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	AssetName     string                 `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestId        string                 `protobuf:"bytes,4,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetTransactionQxTransfer) Reset() {
	*x = AssetTransactionQxTransfer{}
	mi := &file_heatwallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetTransactionQxTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetTransactionQxTransfer) ProtoMessage() {}

func (x *AssetTransactionQxTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_heatwallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetTransactionQxTransfer.ProtoReflect.Descriptor instead.
func (*AssetTransactionQxTransfer) Descriptor() ([]byte, []int) {
	return file_heatwallet_proto_rawDescGZIP(), []int{1}
}

func (x *AssetTransactionQxTransfer) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

func (x *AssetTransactionQxTransfer) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *AssetTransactionQxTransfer) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *AssetTransactionQxTransfer) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *AssetTransactionQxTransfer) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetIdentityAssetTransactionsRequestV2 struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Identity                  string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	AssetIssuer               string                 `protobuf:"bytes,2,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	AssetName                 string                 `protobuf:"bytes,3,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	EndTick                   uint32                 `protobuf:"varint,4,opt,name=end_tick,json=endTick,proto3" json:"end_tick,omitempty"`
	TxnIndexStart             uint32                 `protobuf:"varint,5,opt,name=txn_index_start,json=txnIndexStart,proto3" json:"txn_index_start,omitempty"`
	MaxTransactions           uint32                 `protobuf:"varint,6,opt,name=max_transactions,json=maxTransactions,proto3" json:"max_transactions,omitempty"`
	IncludeFailedTransactions bool                   `protobuf:"varint,7,opt,name=include_failed_transactions,json=includeFailedTransactions,proto3" json:"include_failed_transactions,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetIdentityAssetTransactionsRequestV2) Reset() {
	*x = GetIdentityAssetTransactionsRequestV2{}
	mi := &file_heatwallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityAssetTransactionsRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityAssetTransactionsRequestV2) ProtoMessage() {}

func (x *GetIdentityAssetTransactionsRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_heatwallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityAssetTransactionsRequestV2.ProtoReflect.Descriptor instead.
func (*GetIdentityAssetTransactionsRequestV2) Descriptor() ([]byte, []int) {
	return file_heatwallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetIdentityAssetTransactionsRequestV2) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetIdentityAssetTransactionsRequestV2) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

func (x *GetIdentityAssetTransactionsRequestV2) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *GetIdentityAssetTransactionsRequestV2) GetEndTick() uint32 {
	if x != nil {
		return x.EndTick
	}
	return 0
}

func (x *GetIdentityAssetTransactionsRequestV2) GetTxnIndexStart() uint32 {
	if x != nil {
		return x.TxnIndexStart
	}
	return 0
}

func (x *GetIdentityAssetTransactionsRequestV2) GetMaxTransactions() uint32 {
	if x != nil {
		return x.MaxTransactions
	}
	return 0
}

func (x *GetIdentityAssetTransactionsRequestV2) GetIncludeFailedTransactions() bool {
	if x != nil {
		return x.IncludeFailedTransactions
	}
	return false
}

type GetIdentityAssetTransactionsResponseV2 struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CurrentTick       uint32                 `protobuf:"varint,1,opt,name=current_tick,json=currentTick,proto3" json:"current_tick,omitempty"`
	NextEndTick       uint32                 `protobuf:"varint,2,opt,name=next_end_tick,json=nextEndTick,proto3" json:"next_end_tick,omitempty"`
	NextTxnIndexStart uint32                 `protobuf:"varint,3,opt,name=next_txn_index_start,json=nextTxnIndexStart,proto3" json:"next_txn_index_start,omitempty"`
	Transactions      []*AssetTransaction    `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetIdentityAssetTransactionsResponseV2) Reset() {
	*x = GetIdentityAssetTransactionsResponseV2{}
	mi := &file_heatwallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityAssetTransactionsResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityAssetTransactionsResponseV2) ProtoMessage() {}

func (x *GetIdentityAssetTransactionsResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_heatwallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityAssetTransactionsResponseV2.ProtoReflect.Descriptor instead.
func (*GetIdentityAssetTransactionsResponseV2) Descriptor() ([]byte, []int) {
	return file_heatwallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetIdentityAssetTransactionsResponseV2) GetCurrentTick() uint32 {
	if x != nil {
		return x.CurrentTick
	}
	return 0
}

func (x *GetIdentityAssetTransactionsResponseV2) GetNextEndTick() uint32 {
	if x != nil {
		return x.NextEndTick
	}
	return 0
}

func (x *GetIdentityAssetTransactionsResponseV2) GetNextTxnIndexStart() uint32 {
	if x != nil {
		return x.NextTxnIndexStart
	}
	return 0
}

func (x *GetIdentityAssetTransactionsResponseV2) GetTransactions() []*AssetTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type AssetTransactionsPerTickDB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []string               `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetTransactionsPerTickDB) Reset() {
	*x = AssetTransactionsPerTickDB{}
	mi := &file_heatwallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetTransactionsPerTickDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetTransactionsPerTickDB) ProtoMessage() {}

func (x *AssetTransactionsPerTickDB) ProtoReflect() protoreflect.Message {
	mi := &file_heatwallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetTransactionsPerTickDB.ProtoReflect.Descriptor instead.
func (*AssetTransactionsPerTickDB) Descriptor() ([]byte, []int) {
	return file_heatwallet_proto_rawDescGZIP(), []int{4}
}

func (x *AssetTransactionsPerTickDB) GetTransactions() []string {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_heatwallet_proto protoreflect.FileDescriptor

const file_heatwallet_proto_rawDesc = "" +
	"\n" +
	"\x10heatwallet.proto\x12\x19qubic.archiver.archive.pb\x1a\x1cgoogle/api/annotations.proto\x1a\rarchive.proto\"\xbf\x03\n" +
	"\x10AssetTransaction\x12Z\n" +
	"\x10transaction_type\x18\x01 \x01(\x0e2/.qubic.archiver.archive.pb.AssetTransactionTypeR\x0ftransactionType\x12H\n" +
	"\vtransaction\x18\x02 \x01(\v2&.qubic.archiver.archive.pb.TransactionR\vtransaction\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"money_flew\x18\x04 \x01(\bR\tmoneyFlew\x12X\n" +
	"\x0fqutil_send_many\x18\x05 \x01(\v2..qubic.archiver.archive.pb.SendManyTransactionH\x00R\rqutilSendMany\x12c\n" +
	"\x11qx_asset_transfer\x18\x06 \x01(\v25.qubic.archiver.archive.pb.AssetTransactionQxTransferH\x00R\x0fqxAssetTransferB\t\n" +
	"\apayload\"\xac\x01\n" +
	"\x1aAssetTransactionQxTransfer\x12!\n" +
	"\fasset_issuer\x18\x01 \x01(\tR\vassetIssuer\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x17\n" +
	"\adest_id\x18\x04 \x01(\tR\x06destId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x04R\x06amount\"\xb3\x02\n" +
	"%GetIdentityAssetTransactionsRequestV2\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12!\n" +
	"\fasset_issuer\x18\x02 \x01(\tR\vassetIssuer\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x03 \x01(\tR\tassetName\x12\x19\n" +
	"\bend_tick\x18\x04 \x01(\rR\aendTick\x12&\n" +
	"\x0ftxn_index_start\x18\x05 \x01(\rR\rtxnIndexStart\x12)\n" +
	"\x10max_transactions\x18\x06 \x01(\rR\x0fmaxTransactions\x12>\n" +
	"\x1binclude_failed_transactions\x18\a \x01(\bR\x19includeFailedTransactions\"\xf1\x01\n" +
	"&GetIdentityAssetTransactionsResponseV2\x12!\n" +
	"\fcurrent_tick\x18\x01 \x01(\rR\vcurrentTick\x12\"\n" +
	"\rnext_end_tick\x18\x02 \x01(\rR\vnextEndTick\x12/\n" +
	"\x14next_txn_index_start\x18\x03 \x01(\rR\x11nextTxnIndexStart\x12O\n" +
	"\ftransactions\x18\x04 \x03(\v2+.qubic.archiver.archive.pb.AssetTransactionR\ftransactions\"@\n" +
	"\x1aAssetTransactionsPerTickDB\x12\"\n" +
	"\ftransactions\x18\x01 \x03(\tR\ftransactions*W\n" +
	"\x14AssetTransactionType\x12\x13\n" +
	"\x0fNATIVE_TRANSFER\x10\x00\x12\x13\n" +
	"\x0fQUTIL_SEND_MANY\x10\x01\x12\x15\n" +
	"\x11QX_ASSET_TRANSFER\x10\x022\x8d\x02\n" +
	"\x11HeatwalletService\x12\xf7\x01\n" +
	"\x1eGetIdentityAssetTransactionsV2\x12@.qubic.archiver.archive.pb.GetIdentityAssetTransactionsRequestV2\x1aA.qubic.archiver.archive.pb.GetIdentityAssetTransactionsResponseV2\"P\x82\xd3\xe4\x93\x02J\x12H/v2/identities/{identity}/{asset_issuer}/{asset_name}/asset-transactionsB3Z1github.com/dmdeklerk/go-archiver/heatwallet/protob\x06proto3"

var (
	file_heatwallet_proto_rawDescOnce sync.Once
	file_heatwallet_proto_rawDescData []byte
)

func file_heatwallet_proto_rawDescGZIP() []byte {
	file_heatwallet_proto_rawDescOnce.Do(func() {
		file_heatwallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heatwallet_proto_rawDesc), len(file_heatwallet_proto_rawDesc)))
	})
	return file_heatwallet_proto_rawDescData
}

var file_heatwallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_heatwallet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_heatwallet_proto_goTypes = []any{
	(AssetTransactionType)(0),                      // 0: qubic.archiver.archive.pb.AssetTransactionType
	(*AssetTransaction)(nil),                       // 1: qubic.archiver.archive.pb.AssetTransaction
	(*AssetTransactionQxTransfer)(nil),             // 2: qubic.archiver.archive.pb.AssetTransactionQxTransfer
	(*GetIdentityAssetTransactionsRequestV2)(nil),  // 3: qubic.archiver.archive.pb.GetIdentityAssetTransactionsRequestV2
	(*GetIdentityAssetTransactionsResponseV2)(nil), // 4: qubic.archiver.archive.pb.GetIdentityAssetTransactionsResponseV2
	(*AssetTransactionsPerTickDB)(nil),             // 5: qubic.archiver.archive.pb.AssetTransactionsPerTickDB
	(*protobuff.Transaction)(nil),                  // 6: qubic.archiver.archive.pb.Transaction
	(*protobuff.SendManyTransaction)(nil),          // 7: qubic.archiver.archive.pb.SendManyTransaction
}
var file_heatwallet_proto_depIdxs = []int32{
	0, // 0: qubic.archiver.archive.pb.AssetTransaction.transaction_type:type_name -> qubic.archiver.archive.pb.AssetTransactionType
	6, // 1: qubic.archiver.archive.pb.AssetTransaction.transaction:type_name -> qubic.archiver.archive.pb.Transaction
	7, // 2: qubic.archiver.archive.pb.AssetTransaction.qutil_send_many:type_name -> qubic.archiver.archive.pb.SendManyTransaction
	2, // 3: qubic.archiver.archive.pb.AssetTransaction.qx_asset_transfer:type_name -> qubic.archiver.archive.pb.AssetTransactionQxTransfer
	1, // 4: qubic.archiver.archive.pb.GetIdentityAssetTransactionsResponseV2.transactions:type_name -> qubic.archiver.archive.pb.AssetTransaction
	3, // 5: qubic.archiver.archive.pb.HeatwalletService.GetIdentityAssetTransactionsV2:input_type -> qubic.archiver.archive.pb.GetIdentityAssetTransactionsRequestV2
	4, // 6: qubic.archiver.archive.pb.HeatwalletService.GetIdentityAssetTransactionsV2:output_type -> qubic.archiver.archive.pb.GetIdentityAssetTransactionsResponseV2
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_heatwallet_proto_init() }
func file_heatwallet_proto_init() {
	if File_heatwallet_proto != nil {
		return
	}
	file_heatwallet_proto_msgTypes[0].OneofWrappers = []any{
		(*AssetTransaction_QutilSendMany)(nil),
		(*AssetTransaction_QxAssetTransfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heatwallet_proto_rawDesc), len(file_heatwallet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heatwallet_proto_goTypes,
		DependencyIndexes: file_heatwallet_proto_depIdxs,
		EnumInfos:         file_heatwallet_proto_enumTypes,
		MessageInfos:      file_heatwallet_proto_msgTypes,
	}.Build()
	File_heatwallet_proto = out.File
	file_heatwallet_proto_goTypes = nil
	file_heatwallet_proto_depIdxs = nil
}
