// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: heatwallet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HeatwalletService_GetIdentityAssetTransactionsV2_FullMethodName = "/qubic.archiver.archive.pb.HeatwalletService/GetIdentityAssetTransactionsV2"
)

// HeatwalletServiceClient is the client API for HeatwalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeatwalletServiceClient interface {
	GetIdentityAssetTransactionsV2(ctx context.Context, in *GetIdentityAssetTransactionsRequestV2, opts ...grpc.CallOption) (*GetIdentityAssetTransactionsResponseV2, error)
}

type heatwalletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeatwalletServiceClient(cc grpc.ClientConnInterface) HeatwalletServiceClient {
	return &heatwalletServiceClient{cc}
}

func (c *heatwalletServiceClient) GetIdentityAssetTransactionsV2(ctx context.Context, in *GetIdentityAssetTransactionsRequestV2, opts ...grpc.CallOption) (*GetIdentityAssetTransactionsResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdentityAssetTransactionsResponseV2)
	err := c.cc.Invoke(ctx, HeatwalletService_GetIdentityAssetTransactionsV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeatwalletServiceServer is the server API for HeatwalletService service.
// All implementations must embed UnimplementedHeatwalletServiceServer
// for forward compatibility.
type HeatwalletServiceServer interface {
	GetIdentityAssetTransactionsV2(context.Context, *GetIdentityAssetTransactionsRequestV2) (*GetIdentityAssetTransactionsResponseV2, error)
	mustEmbedUnimplementedHeatwalletServiceServer()
}

// UnimplementedHeatwalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeatwalletServiceServer struct{}

func (UnimplementedHeatwalletServiceServer) GetIdentityAssetTransactionsV2(context.Context, *GetIdentityAssetTransactionsRequestV2) (*GetIdentityAssetTransactionsResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentityAssetTransactionsV2 not implemented")
}
func (UnimplementedHeatwalletServiceServer) mustEmbedUnimplementedHeatwalletServiceServer() {}
func (UnimplementedHeatwalletServiceServer) testEmbeddedByValue()                           {}

// UnsafeHeatwalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeatwalletServiceServer will
// result in compilation errors.
type UnsafeHeatwalletServiceServer interface {
	mustEmbedUnimplementedHeatwalletServiceServer()
}

func RegisterHeatwalletServiceServer(s grpc.ServiceRegistrar, srv HeatwalletServiceServer) {
	// If the following call pancis, it indicates UnimplementedHeatwalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HeatwalletService_ServiceDesc, srv)
}

func _HeatwalletService_GetIdentityAssetTransactionsV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityAssetTransactionsRequestV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeatwalletServiceServer).GetIdentityAssetTransactionsV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeatwalletService_GetIdentityAssetTransactionsV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeatwalletServiceServer).GetIdentityAssetTransactionsV2(ctx, req.(*GetIdentityAssetTransactionsRequestV2))
	}
	return interceptor(ctx, in, info, handler)
}

// HeatwalletService_ServiceDesc is the grpc.ServiceDesc for HeatwalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeatwalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qubic.archiver.archive.pb.HeatwalletService",
	HandlerType: (*HeatwalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIdentityAssetTransactionsV2",
			Handler:    _HeatwalletService_GetIdentityAssetTransactionsV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heatwallet.proto",
}
