// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: archive.db.proto

package protobuff

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QxAssetTransferDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceId string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestId   string `protobuf:"bytes,2,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	Amount   uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TxId     string `protobuf:"bytes,4,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
}

func (x *QxAssetTransferDB) Reset() {
	*x = QxAssetTransferDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_archive_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QxAssetTransferDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QxAssetTransferDB) ProtoMessage() {}

func (x *QxAssetTransferDB) ProtoReflect() protoreflect.Message {
	mi := &file_archive_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QxAssetTransferDB.ProtoReflect.Descriptor instead.
func (*QxAssetTransferDB) Descriptor() ([]byte, []int) {
	return file_archive_db_proto_rawDescGZIP(), []int{0}
}

func (x *QxAssetTransferDB) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *QxAssetTransferDB) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *QxAssetTransferDB) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *QxAssetTransferDB) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type QxAssetTransfersPerTickDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TickNumber uint32               `protobuf:"varint,1,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	Transfers  []*QxAssetTransferDB `protobuf:"bytes,2,rep,name=transfers,proto3" json:"transfers,omitempty"`
}

func (x *QxAssetTransfersPerTickDB) Reset() {
	*x = QxAssetTransfersPerTickDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_archive_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QxAssetTransfersPerTickDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QxAssetTransfersPerTickDB) ProtoMessage() {}

func (x *QxAssetTransfersPerTickDB) ProtoReflect() protoreflect.Message {
	mi := &file_archive_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QxAssetTransfersPerTickDB.ProtoReflect.Descriptor instead.
func (*QxAssetTransfersPerTickDB) Descriptor() ([]byte, []int) {
	return file_archive_db_proto_rawDescGZIP(), []int{1}
}

func (x *QxAssetTransfersPerTickDB) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

func (x *QxAssetTransfersPerTickDB) GetTransfers() []*QxAssetTransferDB {
	if x != nil {
		return x.Transfers
	}
	return nil
}

var File_archive_db_proto protoreflect.FileDescriptor

var file_archive_db_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1c, 0x71, 0x75, 0x62, 0x69, 0x63, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x72, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x64, 0x62,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x11, 0x51,
	0x78, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x44, 0x42,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x13,
	0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x78, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x19, 0x51, 0x78, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x50, 0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x44,
	0x42, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x4d, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x71, 0x75, 0x62, 0x69, 0x63, 0x2e, 0x61, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x70,
	0x62, 0x2e, 0x64, 0x62, 0x2e, 0x51, 0x78, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x44, 0x42, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x71, 0x75, 0x62, 0x69, 0x63, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_archive_db_proto_rawDescOnce sync.Once
	file_archive_db_proto_rawDescData = file_archive_db_proto_rawDesc
)

func file_archive_db_proto_rawDescGZIP() []byte {
	file_archive_db_proto_rawDescOnce.Do(func() {
		file_archive_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_archive_db_proto_rawDescData)
	})
	return file_archive_db_proto_rawDescData
}

var file_archive_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_archive_db_proto_goTypes = []interface{}{
	(*QxAssetTransferDB)(nil),         // 0: qubic.archiver.archive.pb.db.QxAssetTransferDB
	(*QxAssetTransfersPerTickDB)(nil), // 1: qubic.archiver.archive.pb.db.QxAssetTransfersPerTickDB
}
var file_archive_db_proto_depIdxs = []int32{
	0, // 0: qubic.archiver.archive.pb.db.QxAssetTransfersPerTickDB.transfers:type_name -> qubic.archiver.archive.pb.db.QxAssetTransferDB
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_archive_db_proto_init() }
func file_archive_db_proto_init() {
	if File_archive_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_archive_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QxAssetTransferDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_archive_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QxAssetTransfersPerTickDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_archive_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_archive_db_proto_goTypes,
		DependencyIndexes: file_archive_db_proto_depIdxs,
		MessageInfos:      file_archive_db_proto_msgTypes,
	}.Build()
	File_archive_db_proto = out.File
	file_archive_db_proto_rawDesc = nil
	file_archive_db_proto_goTypes = nil
	file_archive_db_proto_depIdxs = nil
}
